Repository estuary/flow, pull requests merged in 2024-08, with the labels that each got.

#1556 Add two new columns to `connectors` for UI to show/hide properties
  supabase/migrations/06_connectors.sql
  supabase/migrations/58_connector_tags_control_flags.sql
Labels: change:planned

#1591 docs: we no longer require us-east-1 S3 buckets
  site/docs/getting-started/installation.mdx
Labels: docs pending, docs complete / NA

#1593 docs: update source-pendo
  site/docs/reference/Connectors/capture-connectors/README.md
  site/docs/reference/Connectors/capture-connectors/pendo.md
Labels: change:unplanned

#1598 .devcontainer/release.Dockerfile: switch to ubuntu:noble
  .devcontainer/release.Dockerfile
Labels: change:unplanned
