Repository estuary/flow, pull requests merged in 2024-10, with the labels that each got.

#1681 control-plane: make publication_specs_ext work with estuary_support/
  supabase/migrations/67_pub_specs_perf.sql
Labels: control-plane, change:planned

#1683 agent: fix pub status incompatible_collections
  crates/agent/src/controllers/mod.rs
  crates/agent/src/controllers/snapshots/agent__controllers__test__materialization-status-round-trip.snap
  crates/agent/src/controllers/snapshots/agent__controllers__test__status_json_schema.snap
  crates/agent/src/publications/status.rs
Labels: bug, control-plane, change:unplanned

#1684 control-plane: add constraint for grant_capability
  supabase/migrations/68_capability_constraint.sql
Labels: control-plane, change:planned

#1687 agent: add built specs to draft (bugfix)
  crates/agent/src/publications/handler.rs
  crates/agent/src/publications/specs.rs
Labels: bug, control-plane, change:unplanned

#1688 agent: setup rustls CryptoProvider
  Cargo.lock
  crates/agent/Cargo.toml
  crates/agent/src/main.rs
Labels: bug, control-plane, change:unplanned

#1692 flowctl: initialize rustls crypto provider
  Cargo.lock
  crates/flowctl/Cargo.toml
  crates/flowctl/src/main.rs
Labels: bug, flowctl, change:unplanned

#1698 validation: add inferred schema placeholder if needed
  crates/models/src/schemas.rs
  crates/validation/src/collection.rs
Labels: bug, flowctl, change:unplanned

#1704 reactor: show original error when document parse fails
  crates/derive/src/extract_api.rs
Labels: data-plane, change:unplanned

#1705 Fix `flowctl auth ...` not properly exchanging access token for refresh token
  crates/flow-client/src/client.rs
  crates/flowctl/src/auth/mod.rs
  crates/flowctl/src/lib.rs
Labels: bug, flowctl

#1709 improve `automations` interface
  crates/automations/src/executors.rs
  crates/automations/src/lib.rs
  crates/automations/tests/fibonacci.rs
Labels: change:unplanned

#1712 go.mod: bump gazette pin
  go.mod
  go.sum
Labels: change:unplanned

#1714 assemble: correct handling of fragment length
  crates/assemble/src/lib.rs
  crates/validation/tests/model.yaml
  crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap
Labels: change:unplanned

#1720 Johnny/dp timeout
  crates/agent/src/controllers/mod.rs
  crates/agent/src/controllers/publication_status.rs
  crates/agent/src/lib.rs
  crates/agent/src/proxy_connectors.rs
Labels: change:unplanned

#1735 runtime/container: --log-driver=none for connector containers
  crates/runtime/src/container.rs
Labels: change:unplanned

#1741 validation: always overwrite inlined write schema
  crates/models/src/schemas.rs
  crates/validation/tests/scenario_tests.rs
Labels: bug, control-plane, flowctl, change:unplanned
