Repository estuary/flow, pull requests merged in 2024-12, with the labels that each got.

#1805 agent: read connector timeout from env
  crates/agent/src/proxy_connectors.rs
Labels: change:unplanned

#1803 go/protocols/ops: ensure we discard to-long ops logs through the newline
  go/protocols/ops/log_write_adapter.go
  go/protocols/ops/log_write_adapter_test.go
Labels: change:unplanned

#1817 Remove `sso` attribute mapping files and update docs
  sso_readme.md
  supabase/attrMaps/auth0_com.json
Labels: change:planned

#1660 Removing third party hyperlinks from our docs
  site/docs/concepts/captures.md
  site/docs/reference/Connectors/capture-connectors/README.md
  site/docs/reference/Connectors/capture-connectors/Salesforce/salesforce-historical-data.md
  site/docs/reference/Connectors/capture-connectors/airtable.md
  site/docs/reference/Connectors/capture-connectors/amazon-ads.md
  site/docs/reference/Connectors/capture-connectors/amplitude.md
  site/docs/reference/Connectors/capture-connectors/bing-ads.md
  site/docs/reference/Connectors/capture-connectors/braintree.md
  site/docs/reference/Connectors/capture-connectors/braze.md
  site/docs/reference/Connectors/capture-connectors/chargebee.md
  site/docs/reference/Connectors/capture-connectors/confluence.md
  site/docs/reference/Connectors/capture-connectors/exchange-rates.md
  site/docs/reference/Connectors/capture-connectors/facebook-marketing.md
  site/docs/reference/Connectors/capture-connectors/freshdesk.md
  site/docs/reference/Connectors/capture-connectors/github.md
  site/docs/reference/Connectors/capture-connectors/gitlab.md
  site/docs/reference/Connectors/capture-connectors/google-ads.md
  site/docs/reference/Connectors/capture-connectors/google-analytics-4.md
  site/docs/reference/Connectors/capture-connectors/google-analytics.md
  site/docs/reference/Connectors/capture-connectors/google-search-console.md
  site/docs/reference/Connectors/capture-connectors/google-sheets.md
  site/docs/reference/Connectors/capture-connectors/greenhouse.md
  site/docs/reference/Connectors/capture-connectors/harvest.md
  site/docs/reference/Connectors/capture-connectors/hubspot.md
  site/docs/reference/Connectors/capture-connectors/instagram.md
  site/docs/reference/Connectors/capture-connectors/intercom.md
  site/docs/reference/Connectors/capture-connectors/iterable.md
  site/docs/reference/Connectors/capture-connectors/jira.md
  site/docs/reference/Connectors/capture-connectors/klaviyo.md
  site/docs/reference/Connectors/capture-connectors/linkedin-ads.md
  site/docs/reference/Connectors/capture-connectors/linkedin-pages.md
  site/docs/reference/Connectors/capture-connectors/mailchimp.md
  site/docs/reference/Connectors/capture-connectors/marketo.md
  site/docs/reference/Connectors/capture-connectors/mixpanel.md
  site/docs/reference/Connectors/capture-connectors/notion.md
  site/docs/reference/Connectors/capture-connectors/paypal-transaction.md
  site/docs/reference/Connectors/capture-connectors/recharge.md
  site/docs/reference/Connectors/capture-connectors/sendgrid.md
  site/docs/reference/Connectors/capture-connectors/sentry.md
  site/docs/reference/Connectors/capture-connectors/slack.md
  site/docs/reference/Connectors/capture-connectors/snapchat.md
  site/docs/reference/Connectors/capture-connectors/stripe.md
  site/docs/reference/Connectors/capture-connectors/survey-monkey.md
  site/docs/reference/Connectors/capture-connectors/tiktok.md
  site/docs/reference/Connectors/capture-connectors/twilio.md
  site/docs/reference/Connectors/capture-connectors/youtube-analytics.md
  site/docs/reference/Connectors/capture-connectors/zendesk-chat.md
  site/docs/reference/Connectors/capture-connectors/zendesk-support.md
Labels: change:unplanned

#1839 agent: add CONTROL_PLANE_JWT_SECRET to agent-api deployment
  .github/workflows/deploy-agent-api.yaml
Labels: chore, control-plane, change:unplanned, github_actions
