Repository estuary/flow, pull requests merged in 2024-09, with the labels that each got.

#1599 go/runtime: cancel task term if we fail to RestoreCheckpoint
  go/runtime/capture.go
  go/runtime/derive.go
  go/runtime/materialize.go
  go/runtime/task.go
Labels: change:unplanned

#1570 Update `title` and `description` for SEO of documentation site
  site/docs/reference/Connectors/materialization-connectors/MySQL/amazon-rds-mysql.md
  site/docs/reference/Connectors/materialization-connectors/MySQL/google-cloud-sql-mysql.md
  site/docs/reference/Connectors/materialization-connectors/PostgreSQL/PostgreSQL.md
  site/docs/reference/Connectors/materialization-connectors/PostgreSQL/amazon-rds-postgres.md
  site/docs/reference/Connectors/materialization-connectors/PostgreSQL/google-cloud-sql-postgres.md
  site/docs/reference/Connectors/materialization-connectors/SQLServer/amazon-rds-sqlserver.md
  site/docs/reference/Connectors/materialization-connectors/SQLServer/google-cloud-sql-sqlserver.md
  site/docs/reference/Connectors/materialization-connectors/SQLServer/sqlserver.md
  site/docs/reference/Connectors/materialization-connectors/amazon-s3-csv.md
  site/docs/reference/Connectors/materialization-connectors/amazon-s3-iceberg.md
  site/docs/reference/Connectors/materialization-connectors/amazon-s3-parquet.md
  site/docs/reference/Connectors/materialization-connectors/google-gcs-csv.md
  site/docs/reference/Connectors/materialization-connectors/google-gcs-parquet.md
  site/docusaurus.config.js
Labels: change:planned

#1600 crates/sources: extend_from_catalog fixes
  crates/sources/src/merge.rs
  crates/sources/src/merge_test_src.yaml
  crates/sources/src/merge_test_tgt.yaml
  crates/sources/src/snapshots/sources__merge__test__merging.snap
Labels: bug, change:planned

#1606 docs: materialize-s3-iceberg REST catalog
  site/docs/reference/Connectors/materialization-connectors/amazon-s3-iceberg.md
Labels: change:planned

#1608 Removing instructions to materialize logs
  site/docs/reference/working-logs-stats.md
Labels: change:unplanned

#1610 runtime: hard code `materialize-bigquery` in `ser_policy`
  crates/runtime/src/materialize/task.rs
Labels: change:unplanned

#1612 docs: source-zendesk-support ticket_metrics cursor
  site/docs/reference/Connectors/capture-connectors/zendesk-support.md
Labels: change:unplanned

#1211 Disable use of `realtime`
  supabase/migrations/06_connectors.sql
  supabase/migrations/08_discovers.sql
  supabase/migrations/09_publications.sql
  supabase/migrations/15_directives.sql
  supabase/migrations/19_evolutions.sql
Labels: change:unplanned

#1626 fix: `flowctl catalog` does need pagination after all
  crates/flowctl/src/catalog/mod.rs
Labels: change:unplanned

#1636 flowctl: use max build_id for validating local specs
  crates/flowctl/src/local_specs.rs
Labels: bug, flowctl, change:unplanned

#1637 flowctl: Update pagination to use 0-indexed inclusive ranges, and page by response length rather than fixed page size.
  crates/flowctl/src/pagination.rs
Labels: change:unplanned

#1639 agent: fix materialization sourceCapture updates
  crates/agent/src/controllers/materialization.rs
  crates/agent/src/integration_tests/source_captures.rs
Labels: bug, control-plane

#1641 agent: use new pub_id when evolving materializations
  crates/agent/src/controllers/materialization.rs
  crates/agent/src/controllers/publication_status.rs
Labels: bug, control-plane

#1638 dekaf: Gracefully handle invalid connection attempts without shutting down the whole server
  crates/dekaf/src/main.rs
Labels: change:unplanned

#1651 dekaf: Temporarily disable record LZ4 compression
  crates/dekaf/src/read.rs
Labels: change:unplanned

#1649 supabase: add new columns to live_specs_ext and publication_specs_ext views
  supabase/migrations/64_refresh_views.sql
Labels: change:unplanned

#1648 dekaf: Introduce transient error retry limit
  crates/dekaf/src/read.rs
Labels: change:unplanned

#1664 Extend live_specs_ext to include basic data-plane information
  supabase/migrations/65_extend_live_specs_view.sql
Labels: change:planned
