Repository estuary/flow, pull requests merged in 2025-05, with the labels that each got.

#2120 `docs` dependency updates
  site/package-lock.json
Labels: dependencies, change:unplanned

#2127 control plane: only add new tenants to estuary_support/ role
  supabase/migrations/20250502201326_fix-estuary-support.sql
Labels: bug, control-plane

#2150 data-plane-controller: explicitly drop `logs_tx`
  crates/data-plane-controller/src/lib.rs
Labels: change:unplanned

#2180 agent: skip authorization checks for controller-initiated discovers
  crates/agent/src/controlplane.rs
  crates/agent/src/discovers.rs
  crates/agent/src/discovers/executor.rs
  crates/agent/src/integration_tests/harness.rs
Labels: bug, control-plane
